"""
Exports the extra data used by the interactive dashboard (dashboard/).

The main results (metrics, charts, keyword tables) come from
wine_classification.py -> dashboard/data.js. This script rebuilds the same
models with the same split and seed and adds what the interactive features need:

  - per-wine scores on the test set (threshold explorer)
  - confusion counts, top attributes and full tree structure for depth 5..9
    (depth slider + decision-tree prediction in "Predict a wine")
  - Naive Bayes probabilities and SVM weights for every keyword ("Predict a wine")

Every prediction is checked against results/predictions/*.txt so both
dashboards show identical results.

Run (after wine_classification.py):  .venv/bin/python export_interactive_data.py
Output: dashboard/interactive_data.js
"""
import json
import os

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

from wine_classification import (DATA_FILE, SEED, TEST_SIZE, DT_DEPTHS, SVM_C,
                                 PRED, NaiveBayes, load_data)

OUT_DIR = "dashboard"
OUT_FILE = os.path.join(OUT_DIR, "interactive_data.js")


def fix_text(s):
    """Wine names in the spreadsheet are UTF-8 read as cp1252 (e.g. 'CHÃ‚TEAU')."""
    try:
        return s.encode("cp1252").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return s


def counts(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return {"TP": int(tp), "FP": int(fp), "FN": int(fn), "TN": int(tn)}


def check(name, y_te, y_pred):
    """Predictions must match the files written by wine_classification.py."""
    saved = pd.read_csv(os.path.join(PRED, f"{name}_predictions.txt"), sep="\t")
    assert (saved["Real grade"].values == y_te).all(), f"{name}: test labels differ"
    assert (saved["Predicted grade"].values == y_pred).all(), f"{name}: predictions differ"


def r(v, n=5):
    return round(float(v), n)


def main():
    names, Xdf, y = load_data(DATA_FILE)
    features = list(Xdf.columns)
    X = Xdf.values
    X_tr, X_te, y_tr, y_te, n_tr, n_te = train_test_split(
        X, y, names, test_size=TEST_SIZE, stratify=y, random_state=SEED)

    # ---- Naive Bayes
    nb = NaiveBayes(alpha=1.0).fit(X_tr, y_tr)
    nb_prob = nb.predict_proba(X_te)[:, 1]
    check("naive_bayes", y_te, nb.predict(X_te))

    # ---- SVM
    svm = SVC(kernel="linear", C=SVM_C).fit(X_tr, y_tr)
    svm_score = svm.decision_function(X_te)
    check("svm", y_te, svm.predict(X_te))

    # ---- Decision trees, depth 5..9
    trees = {}
    for d in DT_DEPTHS:
        m = DecisionTreeClassifier(criterion="entropy", max_depth=d,
                                   random_state=SEED).fit(X_tr, y_tr)
        yp = m.predict(X_te)
        check(f"decision_tree_depth{d}", y_te, yp)
        t = m.tree_
        imp = pd.Series(m.feature_importances_, index=features)
        imp = imp[imp > 0].sort_values(ascending=False).head(15)
        trees[str(d)] = {
            "counts": counts(y_te, yp),
            "importance": [{"keyword": k, "value": r(v, 4)} for k, v in imp.items()],
            # node arrays: split on feature (x <= 0.5 -> left, i.e. keyword absent)
            "feature": [int(f) for f in t.feature],
            "left": [int(c) for c in t.children_left],
            "right": [int(c) for c in t.children_right],
            "value": [[r(a, 4), r(b, 4)] for a, b in
                      (t.value[:, 0, :] / t.value[:, 0, :].sum(1, keepdims=True))],
            "samples": [int(n) for n in t.n_node_samples],
            "pred": [int(p) for p in yp],
        }

    data = {
        "features": features,
        "nb": {
            "logPrior": [r(v, 8) for v in np.log(nb.prior_)],
            # P(keyword present | class) for class 0 (90-) and class 1 (90+)
            "p1": [[r(a, 8), r(b, 8)] for a, b in zip(nb.p1_[0], nb.p1_[1])],
        },
        "svm": {
            "weights": [r(w, 6) for w in svm.coef_.ravel()],
            "intercept": r(svm.intercept_[0], 6),
        },
        "trees": trees,
        "test": [{
            "name": fix_text(str(n)),
            "label": int(lbl),
            "kw": [int(j) for j in np.flatnonzero(x)],
            "nb": r(p),
            "svm": r(s),
        } for n, lbl, x, p, s in zip(n_te, y_te, X_te, nb_prob, svm_score)],
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Generated by export_interactive_data.py - do not edit by hand.\n")
        f.write("window.WINE_INTERACTIVE = ")
        json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
        f.write(";\n")
    print(f"Predictions verified against {PRED}/. Wrote {OUT_FILE} "
          f"({os.path.getsize(OUT_FILE) / 1024:.0f} KB).")


if __name__ == "__main__":
    main()
