// Generated by wine_classification.py - do not edit by hand.
window.WINE_RESULTS = {
 "dataset": {
  "file": "Full Wine Data.xlsx",
  "wines": 1010,
  "attributes": 305,
  "train": 808,
  "test": 202,
  "seed": 42,
  "folds": 5,
  "testSize": 0.2,
  "pos": 511,
  "neg": 499,
  "trainPos": 409,
  "trainNeg": 399,
  "testPos": 102,
  "testNeg": 100,
  "kwHist": [
   {
    "n": 1,
    "pos": 0,
    "neg": 10
   },
   {
    "n": 2,
    "pos": 1,
    "neg": 47
   },
   {
    "n": 3,
    "pos": 4,
    "neg": 84
   },
   {
    "n": 4,
    "pos": 10,
    "neg": 117
   },
   {
    "n": 5,
    "pos": 30,
    "neg": 113
   },
   {
    "n": 6,
    "pos": 49,
    "neg": 59
   },
   {
    "n": 7,
    "pos": 70,
    "neg": 40
   },
   {
    "n": 8,
    "pos": 79,
    "neg": 17
   },
   {
    "n": 9,
    "pos": 91,
    "neg": 5
   },
   {
    "n": 10,
    "pos": 71,
    "neg": 5
   },
   {
    "n": 11,
    "pos": 49,
    "neg": 2
   },
   {
    "n": 12,
    "pos": 26,
    "neg": 0
   },
   {
    "n": 13,
    "pos": 19,
    "neg": 0
   },
   {
    "n": 14,
    "pos": 9,
    "neg": 0
   },
   {
    "n": 15,
    "pos": 2,
    "neg": 0
   },
   {
    "n": 16,
    "pos": 0,
    "neg": 0
   },
   {
    "n": 17,
    "pos": 0,
    "neg": 0
   },
   {
    "n": 18,
    "pos": 1,
    "neg": 0
   }
  ]
 },
 "models": {
  "Naive Bayes": {
   "label": "Naive Bayes",
   "test": {
    "Accuracy": 0.8713,
    "Precision": 0.9318,
    "Recall (Sensitivity)": 0.8039,
    "Specificity": 0.94,
    "F1-score": 0.8632,
    "TP": 82,
    "FP": 6,
    "FN": 20,
    "TN": 94
   },
   "cv": [
    0.901,
    0.8663,
    0.8713,
    0.8861,
    0.8663
   ],
   "auc": 0.9442,
   "time": 0.00023,
   "roc": [
    [
     0.0,
     0.0
    ],
    [
     0.0,
     0.0098
    ],
    [
     0.0,
     0.5784
    ],
    [
     0.01,
     0.5784
    ],
    [
     0.01,
     0.7647
    ],
    [
     0.02,
     0.7647
    ],
    [
     0.02,
     0.7745
    ],
    [
     0.05,
     0.7745
    ],
    [
     0.05,
     0.8039
    ],
    [
     0.06,
     0.8039
    ],
    [
     0.06,
     0.8333
    ],
    [
     0.07,
     0.8333
    ],
    [
     0.07,
     0.8431
    ],
    [
     0.08,
     0.8431
    ],
    [
     0.08,
     0.8529
    ],
    [
     0.11,
     0.8529
    ],
    [
     0.11,
     0.8725
    ],
    [
     0.13,
     0.8725
    ],
    [
     0.13,
     0.8824
    ],
    [
     0.15,
     0.8824
    ],
    [
     0.15,
     0.8922
    ],
    [
     0.16,
     0.8922
    ],
    [
     0.16,
     0.902
    ],
    [
     0.18,
     0.902
    ],
    [
     0.18,
     0.9216
    ],
    [
     0.19,
     0.9216
    ],
    [
     0.19,
     0.9314
    ],
    [
     0.3,
     0.9314
    ],
    [
     0.3,
     0.951
    ],
    [
     0.35,
     0.951
    ],
    [
     0.35,
     0.9608
    ],
    [
     0.39,
     0.9608
    ],
    [
     0.39,
     0.9706
    ],
    [
     0.71,
     0.9706
    ],
    [
     0.71,
     0.9804
    ],
    [
     0.81,
     0.9804
    ],
    [
     0.81,
     0.9902
    ],
    [
     0.93,
     0.9902
    ],
    [
     0.93,
     1.0
    ],
    [
     1.0,
     1.0
    ]
   ]
  },
  "Decision Tree": {
   "label": "Decision Tree (depth 9)",
   "test": {
    "Accuracy": 0.7277,
    "Precision": 0.8219,
    "Recall (Sensitivity)": 0.5882,
    "Specificity": 0.87,
    "F1-score": 0.6857,
    "TP": 60,
    "FP": 13,
    "FN": 42,
    "TN": 87
   },
   "cv": [
    0.7574,
    0.8069,
    0.7822,
    0.8267,
    0.7426
   ],
   "auc": 0.7398,
   "time": 0.00305,
   "roc": [
    [
     0.0,
     0.0
    ],
    [
     0.11,
     0.5784
    ],
    [
     0.13,
     0.5882
    ],
    [
     0.13,
     0.598
    ],
    [
     0.72,
     0.8922
    ],
    [
     1.0,
     0.9412
    ],
    [
     1.0,
     1.0
    ]
   ]
  },
  "SVM": {
   "label": "SVM (linear)",
   "test": {
    "Accuracy": 0.8663,
    "Precision": 0.8947,
    "Recall (Sensitivity)": 0.8333,
    "Specificity": 0.9,
    "F1-score": 0.8629,
    "TP": 85,
    "FP": 10,
    "FN": 17,
    "TN": 90
   },
   "cv": [
    0.8564,
    0.8861,
    0.8861,
    0.896,
    0.802
   ],
   "auc": 0.9238,
   "time": 0.01543,
   "roc": [
    [
     0.0,
     0.0
    ],
    [
     0.0,
     0.0098
    ],
    [
     0.0,
     0.4412
    ],
    [
     0.02,
     0.4412
    ],
    [
     0.02,
     0.5196
    ],
    [
     0.03,
     0.5196
    ],
    [
     0.03,
     0.6471
    ],
    [
     0.04,
     0.6471
    ],
    [
     0.04,
     0.7157
    ],
    [
     0.05,
     0.7157
    ],
    [
     0.05,
     0.8235
    ],
    [
     0.07,
     0.8235
    ],
    [
     0.07,
     0.8333
    ],
    [
     0.11,
     0.8333
    ],
    [
     0.11,
     0.8431
    ],
    [
     0.14,
     0.8431
    ],
    [
     0.14,
     0.8529
    ],
    [
     0.2,
     0.8529
    ],
    [
     0.2,
     0.8725
    ],
    [
     0.23,
     0.8725
    ],
    [
     0.23,
     0.8824
    ],
    [
     0.27,
     0.8824
    ],
    [
     0.27,
     0.8922
    ],
    [
     0.34,
     0.8922
    ],
    [
     0.34,
     0.902
    ],
    [
     0.39,
     0.902
    ],
    [
     0.39,
     0.9118
    ],
    [
     0.4,
     0.9118
    ],
    [
     0.4,
     0.9314
    ],
    [
     0.42,
     0.9314
    ],
    [
     0.42,
     0.951
    ],
    [
     0.43,
     0.951
    ],
    [
     0.43,
     0.9608
    ],
    [
     0.45,
     0.9608
    ],
    [
     0.45,
     0.9706
    ],
    [
     0.5,
     0.9706
    ],
    [
     0.5,
     0.9804
    ],
    [
     0.68,
     0.9804
    ],
    [
     0.68,
     0.9902
    ],
    [
     0.74,
     0.9902
    ],
    [
     0.74,
     1.0
    ],
    [
     1.0,
     1.0
    ]
   ]
  }
 },
 "nb": {
  "alpha": [
   {
    "alpha": 0.01,
    "cv": 0.8624
   },
   {
    "alpha": 0.1,
    "cv": 0.8713
   },
   {
    "alpha": 0.5,
    "cv": 0.8792
   },
   {
    "alpha": 1,
    "cv": 0.8782
   },
   {
    "alpha": 2,
    "cv": 0.8723
   },
   {
    "alpha": 5,
    "cv": 0.8574
   },
   {
    "alpha": 10,
    "cv": 0.8079
   }
  ],
  "topKeywords": [
   {
    "keyword": "MEDIUM-BODIED",
    "value": -2.5896
   },
   {
    "keyword": "CHALKY",
    "value": -1.8164
   },
   {
    "keyword": "STRAWBERRY",
    "value": -1.6341
   },
   {
    "keyword": "DAMSON PLUM",
    "value": -1.6341
   },
   {
    "keyword": "DANCE",
    "value": -1.4109
   },
   {
    "keyword": "LIGHT-BODIED",
    "value": -1.2731
   },
   {
    "keyword": "CHERRY PIE",
    "value": -1.1232
   },
   {
    "keyword": "CITRUS BLOSSOM",
    "value": -1.1232
   },
   {
    "keyword": "COCOA",
    "value": -1.1232
   },
   {
    "keyword": "FRESH-CUT APPLE",
    "value": -1.1232
   },
   {
    "keyword": "CONCENTRATED",
    "value": 2.748
   },
   {
    "keyword": "FULL-BODIED",
    "value": 2.748
   },
   {
    "keyword": "INTENSE",
    "value": 2.8657
   },
   {
    "keyword": "DENSE",
    "value": 2.8657
   },
   {
    "keyword": "HARMONY",
    "value": 2.9198
   },
   {
    "keyword": "GORGEOUS",
    "value": 3.0664
   },
   {
    "keyword": "ELEGANT",
    "value": 3.2712
   },
   {
    "keyword": "LONG",
    "value": 3.3985
   },
   {
    "keyword": "BEAUTY",
    "value": 3.4411
   },
   {
    "keyword": "POWER",
    "value": 3.5017
   }
  ]
 },
 "dt": {
  "bestDepth": 9,
  "depths": [
   {
    "depth": 5,
    "train": 0.771,
    "test": 0.703,
    "precision": 0.8621,
    "recall": 0.4902,
    "specificity": 0.92,
    "f1": 0.625,
    "cvMean": 0.7455,
    "cvStd": 0.0278,
    "leaves": 16
   },
   {
    "depth": 6,
    "train": 0.8007,
    "test": 0.7178,
    "precision": 0.8462,
    "recall": 0.5392,
    "specificity": 0.9,
    "f1": 0.6587,
    "cvMean": 0.7614,
    "cvStd": 0.0204,
    "leaves": 22
   },
   {
    "depth": 7,
    "train": 0.8255,
    "test": 0.7426,
    "precision": 0.8571,
    "recall": 0.5882,
    "specificity": 0.9,
    "f1": 0.6977,
    "cvMean": 0.7594,
    "cvStd": 0.0244,
    "leaves": 30
   },
   {
    "depth": 8,
    "train": 0.8441,
    "test": 0.7525,
    "precision": 0.8611,
    "recall": 0.6078,
    "specificity": 0.9,
    "f1": 0.7126,
    "cvMean": 0.7802,
    "cvStd": 0.0283,
    "leaves": 35
   },
   {
    "depth": 9,
    "train": 0.8601,
    "test": 0.7277,
    "precision": 0.8219,
    "recall": 0.5882,
    "specificity": 0.87,
    "f1": 0.6857,
    "cvMean": 0.7832,
    "cvStd": 0.0309,
    "leaves": 41
   }
  ],
  "importance": [
   {
    "keyword": "LONG",
    "value": 0.1853
   },
   {
    "keyword": "APRICOT",
    "value": 0.1123
   },
   {
    "keyword": "RICH",
    "value": 0.0917
   },
   {
    "keyword": "LONG FINISH",
    "value": 0.0917
   },
   {
    "keyword": "LIGHT-BODIED",
    "value": 0.0581
   },
   {
    "keyword": "PURE",
    "value": 0.0509
   },
   {
    "keyword": "BEAUTY",
    "value": 0.044
   },
   {
    "keyword": "DELICATE",
    "value": 0.0372
   },
   {
    "keyword": "BLACKBERRY",
    "value": 0.0353
   },
   {
    "keyword": "LENGTH",
    "value": 0.0289
   },
   {
    "keyword": "EXPRESSIVE",
    "value": 0.0275
   },
   {
    "keyword": "FRESH",
    "value": 0.0208
   },
   {
    "keyword": "BRIOCHE",
    "value": 0.0205
   },
   {
    "keyword": "CRISP",
    "value": 0.0171
   },
   {
    "keyword": "SPICE",
    "value": 0.0161
   }
  ]
 },
 "svm": {
  "supportVectors": 282,
  "kernels": [
   {
    "kernel": "linear",
    "C": 0.01,
    "cv": 0.8208,
    "std": 0.0231
   },
   {
    "kernel": "linear",
    "C": 0.1,
    "cv": 0.8564,
    "std": 0.0289
   },
   {
    "kernel": "linear",
    "C": 1.0,
    "cv": 0.8653,
    "std": 0.0344
   },
   {
    "kernel": "linear",
    "C": 10.0,
    "cv": 0.8267,
    "std": 0.023
   },
   {
    "kernel": "rbf",
    "C": 0.01,
    "cv": 0.5059,
    "std": 0.002
   },
   {
    "kernel": "rbf",
    "C": 0.1,
    "cv": 0.8743,
    "std": 0.0152
   },
   {
    "kernel": "rbf",
    "C": 1.0,
    "cv": 0.8851,
    "std": 0.0134
   },
   {
    "kernel": "rbf",
    "C": 10.0,
    "cv": 0.8822,
    "std": 0.017
   },
   {
    "kernel": "poly",
    "C": 0.01,
    "cv": 0.5059,
    "std": 0.002
   },
   {
    "kernel": "poly",
    "C": 0.1,
    "cv": 0.6416,
    "std": 0.0274
   },
   {
    "kernel": "poly",
    "C": 1.0,
    "cv": 0.7069,
    "std": 0.022
   },
   {
    "kernel": "poly",
    "C": 10.0,
    "cv": 0.7366,
    "std": 0.0233
   }
  ],
  "topWeights": [
   {
    "keyword": "TOAST",
    "value": -1.0
   },
   {
    "keyword": "RED",
    "value": -0.87
   },
   {
    "keyword": "CURRANT CONFITURE",
    "value": -0.87
   },
   {
    "keyword": "DANCE",
    "value": -0.7471
   },
   {
    "keyword": "WARM",
    "value": -0.7237
   },
   {
    "keyword": "FRESH-CUT APPLE",
    "value": -0.5766
   },
   {
    "keyword": "MEDIUM-BODIED",
    "value": -0.5566
   },
   {
    "keyword": "FIRM",
    "value": -0.516
   },
   {
    "keyword": "LEMON-LIME",
    "value": -0.5027
   },
   {
    "keyword": "SATINY",
    "value": -0.5014
   },
   {
    "keyword": "DARK BERRY",
    "value": 1.213
   },
   {
    "keyword": "DARK",
    "value": 1.2242
   },
   {
    "keyword": "DELICIOUS",
    "value": 1.2648
   },
   {
    "keyword": "VIBRANT",
    "value": 1.3692
   },
   {
    "keyword": "CONCENTRATED",
    "value": 1.3733
   },
   {
    "keyword": "ELEGANT",
    "value": 1.4483
   },
   {
    "keyword": "POWER",
    "value": 1.5314
   },
   {
    "keyword": "LONG",
    "value": 1.5641
   },
   {
    "keyword": "LONG FINISH",
    "value": 1.6599
   },
   {
    "keyword": "FULL-BODIED",
    "value": 1.8293
   }
  ]
 },
 "keywords": {
  "minCount": 10,
  "common": [
   {
    "keyword": "APPLE",
    "all": 190,
    "pos": 96,
    "neg": 94,
    "pctPos": 18.79,
    "pctNeg": 18.84,
    "p90": 0.5053,
    "nb": -0.0246,
    "svm": 0.0493
   },
   {
    "keyword": "LIGHT-BODIED",
    "all": 187,
    "pos": 41,
    "neg": 146,
    "pctPos": 8.02,
    "pctNeg": 29.26,
    "p90": 0.2193,
    "nb": -1.2731,
    "svm": -0.314
   },
   {
    "keyword": "PEAR",
    "all": 179,
    "pos": 74,
    "neg": 105,
    "pctPos": 14.48,
    "pctNeg": 21.04,
    "p90": 0.4134,
    "nb": -0.3588,
    "svm": 0.213
   },
   {
    "keyword": "FRESH",
    "all": 166,
    "pos": 60,
    "neg": 106,
    "pctPos": 11.74,
    "pctNeg": 21.24,
    "p90": 0.3614,
    "nb": -0.7061,
    "svm": -0.4709
   },
   {
    "keyword": "PEACH",
    "all": 155,
    "pos": 91,
    "neg": 64,
    "pctPos": 17.81,
    "pctNeg": 12.83,
    "p90": 0.5871,
    "nb": 0.3282,
    "svm": 0.3716
   },
   {
    "keyword": "SPICE",
    "all": 149,
    "pos": 87,
    "neg": 62,
    "pctPos": 17.03,
    "pctNeg": 12.42,
    "p90": 0.5839,
    "nb": 0.4947,
    "svm": 0.3147
   },
   {
    "keyword": "MELON",
    "all": 133,
    "pos": 68,
    "neg": 65,
    "pctPos": 13.31,
    "pctNeg": 13.03,
    "p90": 0.5113,
    "nb": 0.0285,
    "svm": 0.2098
   },
   {
    "keyword": "MINERAL",
    "all": 130,
    "pos": 109,
    "neg": 21,
    "pctPos": 21.33,
    "pctNeg": 4.21,
    "p90": 0.8385,
    "nb": 1.7461,
    "svm": 0.7272
   },
   {
    "keyword": "ACIDITY",
    "all": 127,
    "pos": 86,
    "neg": 41,
    "pctPos": 16.83,
    "pctNeg": 8.22,
    "p90": 0.6772,
    "nb": 0.8847,
    "svm": 0.515
   },
   {
    "keyword": "RIPE",
    "all": 120,
    "pos": 88,
    "neg": 32,
    "pctPos": 17.22,
    "pctNeg": 6.41,
    "p90": 0.7333,
    "nb": 0.9121,
    "svm": 0.2257
   },
   {
    "keyword": "LONG",
    "all": 116,
    "pos": 114,
    "neg": 2,
    "pctPos": 22.31,
    "pctNeg": 0.4,
    "p90": 0.9828,
    "nb": 3.3985,
    "svm": 1.5641
   },
   {
    "keyword": "WHITE",
    "all": 115,
    "pos": 48,
    "neg": 67,
    "pctPos": 9.39,
    "pctNeg": 13.43,
    "p90": 0.4174,
    "nb": -0.4484,
    "svm": -0.1568
   },
   {
    "keyword": "APRICOT",
    "all": 110,
    "pos": 100,
    "neg": 10,
    "pctPos": 19.57,
    "pctNeg": 2.0,
    "p90": 0.9091,
    "nb": 2.4362,
    "svm": 1.0621
   },
   {
    "keyword": "RICH",
    "all": 106,
    "pos": 96,
    "neg": 10,
    "pctPos": 18.79,
    "pctNeg": 2.0,
    "p90": 0.9057,
    "nb": 2.0686,
    "svm": 0.3986
   },
   {
    "keyword": "CREAM",
    "all": 102,
    "pos": 79,
    "neg": 23,
    "pctPos": 15.46,
    "pctNeg": 4.61,
    "p90": 0.7745,
    "nb": 1.1843,
    "svm": 0.8231
   },
   {
    "keyword": "CITRUS",
    "all": 97,
    "pos": 45,
    "neg": 52,
    "pctPos": 8.81,
    "pctNeg": 10.42,
    "p90": 0.4639,
    "nb": 0.028,
    "svm": 0.0008
   },
   {
    "keyword": "BALANCE",
    "all": 92,
    "pos": 72,
    "neg": 20,
    "pctPos": 14.09,
    "pctNeg": 4.01,
    "p90": 0.7826,
    "nb": 0.9562,
    "svm": 0.7136
   },
   {
    "keyword": "ALMOND",
    "all": 85,
    "pos": 51,
    "neg": 34,
    "pctPos": 9.98,
    "pctNeg": 6.81,
    "p90": 0.6,
    "nb": 0.4718,
    "svm": 0.6061
   },
   {
    "keyword": "CHERRY",
    "all": 85,
    "pos": 38,
    "neg": 47,
    "pctPos": 7.44,
    "pctNeg": 9.42,
    "p90": 0.4471,
    "nb": -0.2282,
    "svm": 0.2284
   },
   {
    "keyword": "FRUIT",
    "all": 83,
    "pos": 62,
    "neg": 21,
    "pctPos": 12.13,
    "pctNeg": 4.21,
    "p90": 0.747,
    "nb": 1.2483,
    "svm": 0.1736
   }
  ],
  "pos": [
   {
    "keyword": "FULL-BODIED",
    "all": 19,
    "pos": 19,
    "neg": 0,
    "pctPos": 3.72,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.748,
    "svm": 1.8293
   },
   {
    "keyword": "GRACE",
    "all": 12,
    "pos": 12,
    "neg": 0,
    "pctPos": 2.35,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.1726,
    "svm": 1.0
   },
   {
    "keyword": "DENSE",
    "all": 20,
    "pos": 20,
    "neg": 0,
    "pctPos": 3.91,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.8657,
    "svm": 0.322
   },
   {
    "keyword": "HARMONY",
    "all": 22,
    "pos": 22,
    "neg": 0,
    "pctPos": 4.31,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.9198,
    "svm": 1.0
   },
   {
    "keyword": "HAZELNUT",
    "all": 10,
    "pos": 10,
    "neg": 0,
    "pctPos": 1.96,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.9213,
    "svm": 0.8529
   },
   {
    "keyword": "POWER",
    "all": 41,
    "pos": 41,
    "neg": 0,
    "pctPos": 8.02,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.5017,
    "svm": 1.5314
   },
   {
    "keyword": "DARK",
    "all": 13,
    "pos": 13,
    "neg": 0,
    "pctPos": 2.54,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.4603,
    "svm": 1.2242
   },
   {
    "keyword": "BEAUTY",
    "all": 39,
    "pos": 39,
    "neg": 0,
    "pctPos": 7.63,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.4411,
    "svm": 1.1383
   },
   {
    "keyword": "BLACK OLIVE",
    "all": 10,
    "pos": 10,
    "neg": 0,
    "pctPos": 1.96,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.0548,
    "svm": 0.2852
   },
   {
    "keyword": "GORGEOUS",
    "all": 22,
    "pos": 22,
    "neg": 0,
    "pctPos": 4.31,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.0664,
    "svm": 0.6151
   },
   {
    "keyword": "FINESSE",
    "all": 11,
    "pos": 11,
    "neg": 0,
    "pctPos": 2.15,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.3733,
    "svm": 1.0325
   },
   {
    "keyword": "LONG",
    "all": 116,
    "pos": 114,
    "neg": 2,
    "pctPos": 22.31,
    "pctNeg": 0.4,
    "p90": 0.9828,
    "nb": 3.3985,
    "svm": 1.5641
   },
   {
    "keyword": "INTENSE",
    "all": 44,
    "pos": 43,
    "neg": 1,
    "pctPos": 8.41,
    "pctNeg": 0.2,
    "p90": 0.9773,
    "nb": 2.8657,
    "svm": 0.5451
   },
   {
    "keyword": "CONCENTRATED",
    "all": 36,
    "pos": 35,
    "neg": 1,
    "pctPos": 6.85,
    "pctNeg": 0.2,
    "p90": 0.9722,
    "nb": 2.748,
    "svm": 1.3733
   },
   {
    "keyword": "ELEGANT",
    "all": 33,
    "pos": 32,
    "neg": 1,
    "pctPos": 6.26,
    "pctNeg": 0.2,
    "p90": 0.9697,
    "nb": 3.2712,
    "svm": 1.4483
   },
   {
    "keyword": "DEPTH",
    "all": 31,
    "pos": 30,
    "neg": 1,
    "pctPos": 5.87,
    "pctNeg": 0.2,
    "p90": 0.9677,
    "nb": 2.5403,
    "svm": 0.9287
   },
   {
    "keyword": "HONEY",
    "all": 56,
    "pos": 54,
    "neg": 2,
    "pctPos": 10.57,
    "pctNeg": 0.4,
    "p90": 0.9643,
    "nb": 2.6144,
    "svm": 1.05
   },
   {
    "keyword": "EXPRESSIVE",
    "all": 23,
    "pos": 22,
    "neg": 1,
    "pctPos": 4.31,
    "pctNeg": 0.2,
    "p90": 0.9565,
    "nb": 2.2267,
    "svm": 1.0976
   },
   {
    "keyword": "COMPLEX",
    "all": 35,
    "pos": 33,
    "neg": 2,
    "pctPos": 6.46,
    "pctNeg": 0.4,
    "p90": 0.9429,
    "nb": 2.1726,
    "svm": 0.934
   },
   {
    "keyword": "FINE",
    "all": 17,
    "pos": 16,
    "neg": 1,
    "pctPos": 3.13,
    "pctNeg": 0.2,
    "p90": 0.9412,
    "nb": 2.0548,
    "svm": 1.0905
   }
  ],
  "neg": [
   {
    "keyword": "MEDIUM-BODIED",
    "all": 14,
    "pos": 0,
    "neg": 14,
    "pctPos": 0.0,
    "pctNeg": 2.81,
    "p90": 0.0,
    "nb": -2.5896,
    "svm": -0.5566
   },
   {
    "keyword": "STRAWBERRY",
    "all": 12,
    "pos": 1,
    "neg": 11,
    "pctPos": 0.2,
    "pctNeg": 2.2,
    "p90": 0.0833,
    "nb": -1.6341,
    "svm": -0.4592
   },
   {
    "keyword": "DRY",
    "all": 16,
    "pos": 3,
    "neg": 13,
    "pctPos": 0.59,
    "pctNeg": 2.61,
    "p90": 0.1875,
    "nb": -1.1232,
    "svm": 0.0264
   },
   {
    "keyword": "LIGHT-BODIED",
    "all": 187,
    "pos": 41,
    "neg": 146,
    "pctPos": 8.02,
    "pctNeg": 29.26,
    "p90": 0.2193,
    "nb": -1.2731,
    "svm": -0.314
   },
   {
    "keyword": "HERBS",
    "all": 59,
    "pos": 14,
    "neg": 45,
    "pctPos": 2.74,
    "pctNeg": 9.02,
    "p90": 0.2373,
    "nb": -0.9409,
    "svm": -0.0594
   },
   {
    "keyword": "REFRESHING",
    "all": 27,
    "pos": 7,
    "neg": 20,
    "pctPos": 1.37,
    "pctNeg": 4.01,
    "p90": 0.2593,
    "nb": -0.7868,
    "svm": 0.3304
   },
   {
    "keyword": "CRISP",
    "all": 54,
    "pos": 16,
    "neg": 38,
    "pctPos": 3.13,
    "pctNeg": 7.62,
    "p90": 0.2963,
    "nb": -0.686,
    "svm": -0.0679
   },
   {
    "keyword": "CLEAN",
    "all": 29,
    "pos": 9,
    "neg": 20,
    "pctPos": 1.76,
    "pctNeg": 4.01,
    "p90": 0.3103,
    "nb": -0.8356,
    "svm": -0.33
   },
   {
    "keyword": "AROMATIC",
    "all": 14,
    "pos": 5,
    "neg": 9,
    "pctPos": 0.98,
    "pctNeg": 1.8,
    "p90": 0.3571,
    "nb": -0.4946,
    "svm": -0.16
   },
   {
    "keyword": "FRESH",
    "all": 166,
    "pos": 60,
    "neg": 106,
    "pctPos": 11.74,
    "pctNeg": 21.24,
    "p90": 0.3614,
    "nb": -0.7061,
    "svm": -0.4709
   },
   {
    "keyword": "ROUND",
    "all": 23,
    "pos": 9,
    "neg": 14,
    "pctPos": 1.76,
    "pctNeg": 2.81,
    "p90": 0.3913,
    "nb": -0.4301,
    "svm": -0.3223
   },
   {
    "keyword": "FLORAL",
    "all": 79,
    "pos": 31,
    "neg": 48,
    "pctPos": 6.07,
    "pctNeg": 9.62,
    "p90": 0.3924,
    "nb": -0.4301,
    "svm": 0.1078
   },
   {
    "keyword": "GREEN APPLE",
    "all": 28,
    "pos": 11,
    "neg": 17,
    "pctPos": 2.15,
    "pctNeg": 3.41,
    "p90": 0.3929,
    "nb": -0.207,
    "svm": 0.4183
   },
   {
    "keyword": "LIME",
    "all": 70,
    "pos": 28,
    "neg": 42,
    "pctPos": 5.48,
    "pctNeg": 8.42,
    "p90": 0.4,
    "nb": -0.4433,
    "svm": 0.0583
   },
   {
    "keyword": "EARTHY",
    "all": 17,
    "pos": 7,
    "neg": 10,
    "pctPos": 1.37,
    "pctNeg": 2.0,
    "p90": 0.4118,
    "nb": -0.1582,
    "svm": 0.1777
   },
   {
    "keyword": "PEAR",
    "all": 179,
    "pos": 74,
    "neg": 105,
    "pctPos": 14.48,
    "pctNeg": 21.04,
    "p90": 0.4134,
    "nb": -0.3588,
    "svm": 0.213
   },
   {
    "keyword": "TOAST",
    "all": 12,
    "pos": 5,
    "neg": 7,
    "pctPos": 0.98,
    "pctNeg": 1.4,
    "p90": 0.4167,
    "nb": -0.5842,
    "svm": -1.0
   },
   {
    "keyword": "WHITE",
    "all": 115,
    "pos": 48,
    "neg": 67,
    "pctPos": 9.39,
    "pctNeg": 13.43,
    "p90": 0.4174,
    "nb": -0.4484,
    "svm": -0.1568
   },
   {
    "keyword": "LIVELY",
    "all": 61,
    "pos": 27,
    "neg": 34,
    "pctPos": 5.28,
    "pctNeg": 6.81,
    "p90": 0.4426,
    "nb": -0.4124,
    "svm": -0.0919
   },
   {
    "keyword": "TOASTY",
    "all": 18,
    "pos": 8,
    "neg": 10,
    "pctPos": 1.57,
    "pctNeg": 2.0,
    "p90": 0.4444,
    "nb": -0.6308,
    "svm": -0.2699
   }
  ],
  "all": [
   {
    "keyword": "APPLE",
    "all": 190,
    "pos": 96,
    "neg": 94,
    "pctPos": 18.79,
    "pctNeg": 18.84,
    "p90": 0.5053,
    "nb": -0.0246,
    "svm": 0.0493
   },
   {
    "keyword": "LIGHT-BODIED",
    "all": 187,
    "pos": 41,
    "neg": 146,
    "pctPos": 8.02,
    "pctNeg": 29.26,
    "p90": 0.2193,
    "nb": -1.2731,
    "svm": -0.314
   },
   {
    "keyword": "PEAR",
    "all": 179,
    "pos": 74,
    "neg": 105,
    "pctPos": 14.48,
    "pctNeg": 21.04,
    "p90": 0.4134,
    "nb": -0.3588,
    "svm": 0.213
   },
   {
    "keyword": "FRESH",
    "all": 166,
    "pos": 60,
    "neg": 106,
    "pctPos": 11.74,
    "pctNeg": 21.24,
    "p90": 0.3614,
    "nb": -0.7061,
    "svm": -0.4709
   },
   {
    "keyword": "PEACH",
    "all": 155,
    "pos": 91,
    "neg": 64,
    "pctPos": 17.81,
    "pctNeg": 12.83,
    "p90": 0.5871,
    "nb": 0.3282,
    "svm": 0.3716
   },
   {
    "keyword": "SPICE",
    "all": 149,
    "pos": 87,
    "neg": 62,
    "pctPos": 17.03,
    "pctNeg": 12.42,
    "p90": 0.5839,
    "nb": 0.4947,
    "svm": 0.3147
   },
   {
    "keyword": "MELON",
    "all": 133,
    "pos": 68,
    "neg": 65,
    "pctPos": 13.31,
    "pctNeg": 13.03,
    "p90": 0.5113,
    "nb": 0.0285,
    "svm": 0.2098
   },
   {
    "keyword": "MINERAL",
    "all": 130,
    "pos": 109,
    "neg": 21,
    "pctPos": 21.33,
    "pctNeg": 4.21,
    "p90": 0.8385,
    "nb": 1.7461,
    "svm": 0.7272
   },
   {
    "keyword": "ACIDITY",
    "all": 127,
    "pos": 86,
    "neg": 41,
    "pctPos": 16.83,
    "pctNeg": 8.22,
    "p90": 0.6772,
    "nb": 0.8847,
    "svm": 0.515
   },
   {
    "keyword": "RIPE",
    "all": 120,
    "pos": 88,
    "neg": 32,
    "pctPos": 17.22,
    "pctNeg": 6.41,
    "p90": 0.7333,
    "nb": 0.9121,
    "svm": 0.2257
   },
   {
    "keyword": "LONG",
    "all": 116,
    "pos": 114,
    "neg": 2,
    "pctPos": 22.31,
    "pctNeg": 0.4,
    "p90": 0.9828,
    "nb": 3.3985,
    "svm": 1.5641
   },
   {
    "keyword": "WHITE",
    "all": 115,
    "pos": 48,
    "neg": 67,
    "pctPos": 9.39,
    "pctNeg": 13.43,
    "p90": 0.4174,
    "nb": -0.4484,
    "svm": -0.1568
   },
   {
    "keyword": "APRICOT",
    "all": 110,
    "pos": 100,
    "neg": 10,
    "pctPos": 19.57,
    "pctNeg": 2.0,
    "p90": 0.9091,
    "nb": 2.4362,
    "svm": 1.0621
   },
   {
    "keyword": "RICH",
    "all": 106,
    "pos": 96,
    "neg": 10,
    "pctPos": 18.79,
    "pctNeg": 2.0,
    "p90": 0.9057,
    "nb": 2.0686,
    "svm": 0.3986
   },
   {
    "keyword": "CREAM",
    "all": 102,
    "pos": 79,
    "neg": 23,
    "pctPos": 15.46,
    "pctNeg": 4.61,
    "p90": 0.7745,
    "nb": 1.1843,
    "svm": 0.8231
   },
   {
    "keyword": "CITRUS",
    "all": 97,
    "pos": 45,
    "neg": 52,
    "pctPos": 8.81,
    "pctNeg": 10.42,
    "p90": 0.4639,
    "nb": 0.028,
    "svm": 0.0008
   },
   {
    "keyword": "BALANCE",
    "all": 92,
    "pos": 72,
    "neg": 20,
    "pctPos": 14.09,
    "pctNeg": 4.01,
    "p90": 0.7826,
    "nb": 0.9562,
    "svm": 0.7136
   },
   {
    "keyword": "ALMOND",
    "all": 85,
    "pos": 51,
    "neg": 34,
    "pctPos": 9.98,
    "pctNeg": 6.81,
    "p90": 0.6,
    "nb": 0.4718,
    "svm": 0.6061
   },
   {
    "keyword": "CHERRY",
    "all": 85,
    "pos": 38,
    "neg": 47,
    "pctPos": 7.44,
    "pctNeg": 9.42,
    "p90": 0.4471,
    "nb": -0.2282,
    "svm": 0.2284
   },
   {
    "keyword": "FRUIT",
    "all": 83,
    "pos": 62,
    "neg": 21,
    "pctPos": 12.13,
    "pctNeg": 4.21,
    "p90": 0.747,
    "nb": 1.2483,
    "svm": 0.1736
   },
   {
    "keyword": "GRAPEFRUIT",
    "all": 80,
    "pos": 37,
    "neg": 43,
    "pctPos": 7.24,
    "pctNeg": 8.62,
    "p90": 0.4625,
    "nb": -0.2344,
    "svm": 0.5319
   },
   {
    "keyword": "FLORAL",
    "all": 79,
    "pos": 31,
    "neg": 48,
    "pctPos": 6.07,
    "pctNeg": 9.62,
    "p90": 0.3924,
    "nb": -0.4301,
    "svm": 0.1078
   },
   {
    "keyword": "LONG FINISH",
    "all": 78,
    "pos": 72,
    "neg": 6,
    "pctPos": 14.09,
    "pctNeg": 1.2,
    "p90": 0.9231,
    "nb": 2.4264,
    "svm": 1.6599
   },
   {
    "keyword": "LINGER",
    "all": 78,
    "pos": 36,
    "neg": 42,
    "pctPos": 7.05,
    "pctNeg": 8.42,
    "p90": 0.4615,
    "nb": -0.1889,
    "svm": 0.2552
   },
   {
    "keyword": "LEMON",
    "all": 73,
    "pos": 43,
    "neg": 30,
    "pctPos": 8.41,
    "pctNeg": 6.01,
    "p90": 0.589,
    "nb": 0.3118,
    "svm": 0.6903
   },
   {
    "keyword": "LIME",
    "all": 70,
    "pos": 28,
    "neg": 42,
    "pctPos": 5.48,
    "pctNeg": 8.42,
    "p90": 0.4,
    "nb": -0.4433,
    "svm": 0.0583
   },
   {
    "keyword": "PLUM",
    "all": 69,
    "pos": 46,
    "neg": 23,
    "pctPos": 9.0,
    "pctNeg": 4.61,
    "p90": 0.6667,
    "nb": 0.6945,
    "svm": 0.6038
   },
   {
    "keyword": "JUICY",
    "all": 68,
    "pos": 39,
    "neg": 29,
    "pctPos": 7.63,
    "pctNeg": 5.81,
    "p90": 0.5735,
    "nb": 0.0887,
    "svm": 0.2325
   },
   {
    "keyword": "WHITE PEACH",
    "all": 66,
    "pos": 37,
    "neg": 29,
    "pctPos": 7.24,
    "pctNeg": 5.81,
    "p90": 0.5606,
    "nb": 0.2938,
    "svm": 0.3827
   },
   {
    "keyword": "LIVELY",
    "all": 61,
    "pos": 27,
    "neg": 34,
    "pctPos": 5.28,
    "pctNeg": 6.81,
    "p90": 0.4426,
    "nb": -0.4124,
    "svm": -0.0919
   },
   {
    "keyword": "HERBS",
    "all": 59,
    "pos": 14,
    "neg": 45,
    "pctPos": 2.74,
    "pctNeg": 9.02,
    "p90": 0.2373,
    "nb": -0.9409,
    "svm": -0.0594
   },
   {
    "keyword": "HONEY",
    "all": 56,
    "pos": 54,
    "neg": 2,
    "pctPos": 10.57,
    "pctNeg": 0.4,
    "p90": 0.9643,
    "nb": 2.6144,
    "svm": 1.05
   },
   {
    "keyword": "STYLE",
    "all": 56,
    "pos": 29,
    "neg": 27,
    "pctPos": 5.68,
    "pctNeg": 5.41,
    "p90": 0.5179,
    "nb": 0.1802,
    "svm": 0.3905
   },
   {
    "keyword": "BUTTER",
    "all": 55,
    "pos": 45,
    "neg": 10,
    "pctPos": 8.81,
    "pctNeg": 2.0,
    "p90": 0.8182,
    "nb": 1.4157,
    "svm": 0.7251
   },
   {
    "keyword": "SWEET",
    "all": 55,
    "pos": 31,
    "neg": 24,
    "pctPos": 6.07,
    "pctNeg": 4.81,
    "p90": 0.5636,
    "nb": 0.1497,
    "svm": -0.0066
   },
   {
    "keyword": "CRISP",
    "all": 54,
    "pos": 16,
    "neg": 38,
    "pctPos": 3.13,
    "pctNeg": 7.62,
    "p90": 0.2963,
    "nb": -0.686,
    "svm": -0.0679
   },
   {
    "keyword": "WELL-STRUCTURED",
    "all": 53,
    "pos": 48,
    "neg": 5,
    "pctPos": 9.39,
    "pctNeg": 1.0,
    "p90": 0.9057,
    "nb": 1.8972,
    "svm": 0.1705
   },
   {
    "keyword": "NICE",
    "all": 53,
    "pos": 35,
    "neg": 18,
    "pctPos": 6.85,
    "pctNeg": 3.61,
    "p90": 0.6604,
    "nb": 0.4718,
    "svm": 0.6723
   },
   {
    "keyword": "BRIGHT",
    "all": 50,
    "pos": 28,
    "neg": 22,
    "pctPos": 5.48,
    "pctNeg": 4.41,
    "p90": 0.56,
    "nb": 0.2498,
    "svm": 0.0546
   },
   {
    "keyword": "BLACKBERRY",
    "all": 50,
    "pos": 46,
    "neg": 4,
    "pctPos": 9.0,
    "pctNeg": 0.8,
    "p90": 0.92,
    "nb": 2.0295,
    "svm": 0.7754
   },
   {
    "keyword": "FOCUSED",
    "all": 49,
    "pos": 39,
    "neg": 10,
    "pctPos": 7.63,
    "pctNeg": 2.0,
    "p90": 0.7959,
    "nb": 1.2281,
    "svm": 0.6187
   },
   {
    "keyword": "TANNINS",
    "all": 47,
    "pos": 43,
    "neg": 4,
    "pctPos": 8.41,
    "pctNeg": 0.8,
    "p90": 0.9149,
    "nb": 2.1154,
    "svm": 0.2999
   },
   {
    "keyword": "INTENSE",
    "all": 44,
    "pos": 43,
    "neg": 1,
    "pctPos": 8.41,
    "pctNeg": 0.2,
    "p90": 0.9773,
    "nb": 2.8657,
    "svm": 0.5451
   },
   {
    "keyword": "PURE",
    "all": 44,
    "pos": 41,
    "neg": 3,
    "pctPos": 8.02,
    "pctNeg": 0.6,
    "p90": 0.9318,
    "nb": 2.1726,
    "svm": 1.0981
   },
   {
    "keyword": "EXCELLENT FINISH",
    "all": 44,
    "pos": 36,
    "neg": 8,
    "pctPos": 7.05,
    "pctNeg": 1.6,
    "p90": 0.8182,
    "nb": 1.2971,
    "svm": -0.0628
   },
   {
    "keyword": "CURRANT",
    "all": 44,
    "pos": 39,
    "neg": 5,
    "pctPos": 7.63,
    "pctNeg": 1.0,
    "p90": 0.8864,
    "nb": 1.5509,
    "svm": 0.8999
   },
   {
    "keyword": "LUSH",
    "all": 42,
    "pos": 38,
    "neg": 4,
    "pctPos": 7.44,
    "pctNeg": 0.8,
    "p90": 0.9048,
    "nb": 1.7999,
    "svm": 0.5449
   },
   {
    "keyword": "SMOKE",
    "all": 42,
    "pos": 28,
    "neg": 14,
    "pctPos": 5.48,
    "pctNeg": 2.81,
    "p90": 0.6667,
    "nb": 0.8356,
    "svm": 0.1326
   },
   {
    "keyword": "POWER",
    "all": 41,
    "pos": 41,
    "neg": 0,
    "pctPos": 8.02,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.5017,
    "svm": 1.5314
   },
   {
    "keyword": "VIBRANT",
    "all": 41,
    "pos": 34,
    "neg": 7,
    "pctPos": 6.65,
    "pctNeg": 1.4,
    "p90": 0.8293,
    "nb": 1.154,
    "svm": 1.3692
   },
   {
    "keyword": "SILKY",
    "all": 39,
    "pos": 24,
    "neg": 15,
    "pctPos": 4.7,
    "pctNeg": 3.01,
    "p90": 0.6154,
    "nb": 0.4862,
    "svm": 0.5137
   },
   {
    "keyword": "PINEAPPLE",
    "all": 39,
    "pos": 18,
    "neg": 21,
    "pctPos": 3.52,
    "pctNeg": 4.21,
    "p90": 0.4615,
    "nb": -0.1965,
    "svm": 0.0653
   },
   {
    "keyword": "BEAUTY",
    "all": 39,
    "pos": 39,
    "neg": 0,
    "pctPos": 7.63,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.4411,
    "svm": 1.1383
   },
   {
    "keyword": "BRIOCHE",
    "all": 38,
    "pos": 25,
    "neg": 13,
    "pctPos": 4.89,
    "pctNeg": 2.61,
    "p90": 0.6579,
    "nb": 0.3808,
    "svm": 0.2324
   },
   {
    "keyword": "CONCENTRATED",
    "all": 36,
    "pos": 35,
    "neg": 1,
    "pctPos": 6.85,
    "pctNeg": 0.2,
    "p90": 0.9722,
    "nb": 2.748,
    "svm": 1.3733
   },
   {
    "keyword": "CHAMOMILE",
    "all": 36,
    "pos": 26,
    "neg": 10,
    "pctPos": 5.09,
    "pctNeg": 2.0,
    "p90": 0.7222,
    "nb": 0.9404,
    "svm": 0.3775
   },
   {
    "keyword": "VANILLA",
    "all": 35,
    "pos": 16,
    "neg": 19,
    "pctPos": 3.13,
    "pctNeg": 3.81,
    "p90": 0.4571,
    "nb": -0.1582,
    "svm": -0.3483
   },
   {
    "keyword": "LAYERS",
    "all": 35,
    "pos": 32,
    "neg": 3,
    "pctPos": 6.26,
    "pctNeg": 0.6,
    "p90": 0.9143,
    "nb": 1.9564,
    "svm": 0.1269
   },
   {
    "keyword": "COMPLEX",
    "all": 35,
    "pos": 33,
    "neg": 2,
    "pctPos": 6.46,
    "pctNeg": 0.4,
    "p90": 0.9429,
    "nb": 2.1726,
    "svm": 0.934
   },
   {
    "keyword": "FIRM",
    "all": 34,
    "pos": 17,
    "neg": 17,
    "pctPos": 3.33,
    "pctNeg": 3.41,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": -0.516
   },
   {
    "keyword": "ELEGANT",
    "all": 33,
    "pos": 32,
    "neg": 1,
    "pctPos": 6.26,
    "pctNeg": 0.2,
    "p90": 0.9697,
    "nb": 3.2712,
    "svm": 1.4483
   },
   {
    "keyword": "LENGTH",
    "all": 33,
    "pos": 29,
    "neg": 4,
    "pctPos": 5.68,
    "pctNeg": 0.8,
    "p90": 0.8788,
    "nb": 2.1726,
    "svm": 0.8338
   },
   {
    "keyword": "RACY",
    "all": 33,
    "pos": 28,
    "neg": 5,
    "pctPos": 5.48,
    "pctNeg": 1.0,
    "p90": 0.8485,
    "nb": 1.5014,
    "svm": 0.6058
   },
   {
    "keyword": "POLISHED",
    "all": 33,
    "pos": 28,
    "neg": 5,
    "pctPos": 5.48,
    "pctNeg": 1.0,
    "p90": 0.8485,
    "nb": 1.3191,
    "svm": 0.4011
   },
   {
    "keyword": "MANGO",
    "all": 32,
    "pos": 28,
    "neg": 4,
    "pctPos": 5.48,
    "pctNeg": 0.8,
    "p90": 0.875,
    "nb": 1.9678,
    "svm": 0.4979
   },
   {
    "keyword": "SPECIFIC FINISH",
    "all": 32,
    "pos": 16,
    "neg": 16,
    "pctPos": 3.13,
    "pctNeg": 3.21,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": 0.214
   },
   {
    "keyword": "RED",
    "all": 31,
    "pos": 17,
    "neg": 14,
    "pctPos": 3.33,
    "pctNeg": 2.81,
    "p90": 0.5484,
    "nb": -0.1917,
    "svm": -0.87
   },
   {
    "keyword": "DEPTH",
    "all": 31,
    "pos": 30,
    "neg": 1,
    "pctPos": 5.87,
    "pctNeg": 0.2,
    "p90": 0.9677,
    "nb": 2.5403,
    "svm": 0.9287
   },
   {
    "keyword": "ORANGE",
    "all": 30,
    "pos": 24,
    "neg": 6,
    "pctPos": 4.7,
    "pctNeg": 1.2,
    "p90": 0.8,
    "nb": 1.3191,
    "svm": 0.3079
   },
   {
    "keyword": "CLEAN",
    "all": 29,
    "pos": 9,
    "neg": 20,
    "pctPos": 1.76,
    "pctNeg": 4.01,
    "p90": 0.3103,
    "nb": -0.8356,
    "svm": -0.33
   },
   {
    "keyword": "GREEN APPLE",
    "all": 28,
    "pos": 11,
    "neg": 17,
    "pctPos": 2.15,
    "pctNeg": 3.41,
    "p90": 0.3929,
    "nb": -0.207,
    "svm": 0.4183
   },
   {
    "keyword": "SUPPLE",
    "all": 28,
    "pos": 26,
    "neg": 2,
    "pctPos": 5.09,
    "pctNeg": 0.4,
    "p90": 0.9286,
    "nb": 2.0548,
    "svm": 0.7431
   },
   {
    "keyword": "TEXTURE",
    "all": 27,
    "pos": 25,
    "neg": 2,
    "pctPos": 4.89,
    "pctNeg": 0.4,
    "p90": 0.9259,
    "nb": 1.9678,
    "svm": -0.2154
   },
   {
    "keyword": "REFRESHING",
    "all": 27,
    "pos": 7,
    "neg": 20,
    "pctPos": 1.37,
    "pctNeg": 4.01,
    "p90": 0.2593,
    "nb": -0.7868,
    "svm": 0.3304
   },
   {
    "keyword": "RASPBERRY",
    "all": 25,
    "pos": 20,
    "neg": 5,
    "pctPos": 3.91,
    "pctNeg": 1.0,
    "p90": 0.8,
    "nb": 0.7486,
    "svm": 0.704
   },
   {
    "keyword": "HONEYSUCKLE",
    "all": 25,
    "pos": 17,
    "neg": 8,
    "pctPos": 3.33,
    "pctNeg": 1.6,
    "p90": 0.68,
    "nb": 0.7291,
    "svm": -0.036
   },
   {
    "keyword": "DISTINCTIVE",
    "all": 23,
    "pos": 15,
    "neg": 8,
    "pctPos": 2.94,
    "pctNeg": 1.6,
    "p90": 0.6522,
    "nb": 0.4862,
    "svm": -0.1726
   },
   {
    "keyword": "DELICATE",
    "all": 23,
    "pos": 16,
    "neg": 7,
    "pctPos": 3.13,
    "pctNeg": 1.4,
    "p90": 0.6957,
    "nb": 0.7486,
    "svm": 1.0586
   },
   {
    "keyword": "EXPRESSIVE",
    "all": 23,
    "pos": 22,
    "neg": 1,
    "pctPos": 4.31,
    "pctNeg": 0.2,
    "p90": 0.9565,
    "nb": 2.2267,
    "svm": 1.0976
   },
   {
    "keyword": "TANGERINE",
    "all": 23,
    "pos": 14,
    "neg": 9,
    "pctPos": 2.74,
    "pctNeg": 1.8,
    "p90": 0.6087,
    "nb": 0.3431,
    "svm": 0.2452
   },
   {
    "keyword": "WHITE PEPPER",
    "all": 23,
    "pos": 12,
    "neg": 11,
    "pctPos": 2.35,
    "pctNeg": 2.2,
    "p90": 0.5217,
    "nb": -0.2478,
    "svm": -0.1184
   },
   {
    "keyword": "ROUND",
    "all": 23,
    "pos": 9,
    "neg": 14,
    "pctPos": 1.76,
    "pctNeg": 2.81,
    "p90": 0.3913,
    "nb": -0.4301,
    "svm": -0.3223
   },
   {
    "keyword": "GORGEOUS",
    "all": 22,
    "pos": 22,
    "neg": 0,
    "pctPos": 4.31,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 3.0664,
    "svm": 0.6151
   },
   {
    "keyword": "INTENSITY",
    "all": 22,
    "pos": 18,
    "neg": 4,
    "pctPos": 3.52,
    "pctNeg": 0.8,
    "p90": 0.8182,
    "nb": 1.2971,
    "svm": 0.4487
   },
   {
    "keyword": "NECTARINE",
    "all": 22,
    "pos": 13,
    "neg": 9,
    "pctPos": 2.54,
    "pctNeg": 1.8,
    "p90": 0.5909,
    "nb": 0.176,
    "svm": 0.0036
   },
   {
    "keyword": "LOVELY",
    "all": 22,
    "pos": 20,
    "neg": 2,
    "pctPos": 3.91,
    "pctNeg": 0.4,
    "p90": 0.9091,
    "nb": 1.7671,
    "svm": 0.7377
   },
   {
    "keyword": "HARMONY",
    "all": 22,
    "pos": 22,
    "neg": 0,
    "pctPos": 4.31,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.9198,
    "svm": 1.0
   },
   {
    "keyword": "ENTICING",
    "all": 22,
    "pos": 18,
    "neg": 4,
    "pctPos": 3.52,
    "pctNeg": 0.8,
    "p90": 0.8182,
    "nb": 1.4794,
    "svm": 0.9642
   },
   {
    "keyword": "GENEROUS",
    "all": 21,
    "pos": 19,
    "neg": 2,
    "pctPos": 3.72,
    "pctNeg": 0.4,
    "p90": 0.9048,
    "nb": 1.9903,
    "svm": 0.5363
   },
   {
    "keyword": "DENSE",
    "all": 20,
    "pos": 20,
    "neg": 0,
    "pctPos": 3.91,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.8657,
    "svm": 0.322
   },
   {
    "keyword": "FULL-BODIED",
    "all": 19,
    "pos": 19,
    "neg": 0,
    "pctPos": 3.72,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.748,
    "svm": 1.8293
   },
   {
    "keyword": "BROAD",
    "all": 19,
    "pos": 10,
    "neg": 9,
    "pctPos": 1.96,
    "pctNeg": 1.8,
    "p90": 0.5263,
    "nb": -0.0246,
    "svm": -0.3601
   },
   {
    "keyword": "SMOOTH",
    "all": 19,
    "pos": 15,
    "neg": 4,
    "pctPos": 2.94,
    "pctNeg": 0.8,
    "p90": 0.7895,
    "nb": 0.9309,
    "svm": 0.3698
   },
   {
    "keyword": "CHOCOLATE",
    "all": 19,
    "pos": 15,
    "neg": 4,
    "pctPos": 2.94,
    "pctNeg": 0.8,
    "p90": 0.7895,
    "nb": 0.7638,
    "svm": 0.0926
   },
   {
    "keyword": "SEAMLESS",
    "all": 19,
    "pos": 17,
    "neg": 2,
    "pctPos": 3.33,
    "pctNeg": 0.4,
    "p90": 0.8947,
    "nb": 1.71,
    "svm": 0.1965
   },
   {
    "keyword": "TOBACCO",
    "all": 18,
    "pos": 12,
    "neg": 6,
    "pctPos": 2.35,
    "pctNeg": 1.2,
    "p90": 0.6667,
    "nb": 0.4862,
    "svm": -0.192
   },
   {
    "keyword": "LEMON CURD",
    "all": 18,
    "pos": 12,
    "neg": 6,
    "pctPos": 2.35,
    "pctNeg": 1.2,
    "p90": 0.6667,
    "nb": 0.4862,
    "svm": 0.5341
   },
   {
    "keyword": "FIG",
    "all": 18,
    "pos": 16,
    "neg": 2,
    "pctPos": 3.13,
    "pctNeg": 0.4,
    "p90": 0.8889,
    "nb": 1.5158,
    "svm": 0.369
   },
   {
    "keyword": "TOASTY",
    "all": 18,
    "pos": 8,
    "neg": 10,
    "pctPos": 1.57,
    "pctNeg": 2.0,
    "p90": 0.4444,
    "nb": -0.6308,
    "svm": -0.2699
   },
   {
    "keyword": "BLACK CHERRY",
    "all": 18,
    "pos": 14,
    "neg": 4,
    "pctPos": 2.74,
    "pctNeg": 0.8,
    "p90": 0.7778,
    "nb": 0.987,
    "svm": 0.1758
   },
   {
    "keyword": "SUBTLE",
    "all": 18,
    "pos": 13,
    "neg": 5,
    "pctPos": 2.54,
    "pctNeg": 1.0,
    "p90": 0.7222,
    "nb": 0.6685,
    "svm": 0.3588
   },
   {
    "keyword": "SAVORY",
    "all": 18,
    "pos": 13,
    "neg": 5,
    "pctPos": 2.54,
    "pctNeg": 1.0,
    "p90": 0.7222,
    "nb": 0.987,
    "svm": 0.3747
   },
   {
    "keyword": "MOUTHWATERING",
    "all": 18,
    "pos": 16,
    "neg": 2,
    "pctPos": 3.13,
    "pctNeg": 0.4,
    "p90": 0.8889,
    "nb": 2.0548,
    "svm": 0.626
   },
   {
    "keyword": "EARTHY",
    "all": 17,
    "pos": 7,
    "neg": 10,
    "pctPos": 1.37,
    "pctNeg": 2.0,
    "p90": 0.4118,
    "nb": -0.1582,
    "svm": 0.1777
   },
   {
    "keyword": "FINE",
    "all": 17,
    "pos": 16,
    "neg": 1,
    "pctPos": 3.13,
    "pctNeg": 0.2,
    "p90": 0.9412,
    "nb": 2.0548,
    "svm": 1.0905
   },
   {
    "keyword": "TIGHT",
    "all": 16,
    "pos": 13,
    "neg": 3,
    "pctPos": 2.54,
    "pctNeg": 0.6,
    "p90": 0.8125,
    "nb": 1.2281,
    "svm": 0.3989
   },
   {
    "keyword": "SLEEK",
    "all": 16,
    "pos": 13,
    "neg": 3,
    "pctPos": 2.54,
    "pctNeg": 0.6,
    "p90": 0.8125,
    "nb": 1.2747,
    "svm": 0.9072
   },
   {
    "keyword": "ORANGE PEEL",
    "all": 16,
    "pos": 14,
    "neg": 2,
    "pctPos": 2.74,
    "pctNeg": 0.4,
    "p90": 0.875,
    "nb": 1.4417,
    "svm": 0.5853
   },
   {
    "keyword": "ACCENTS",
    "all": 16,
    "pos": 11,
    "neg": 5,
    "pctPos": 2.15,
    "pctNeg": 1.0,
    "p90": 0.6875,
    "nb": 0.7638,
    "svm": 0.4154
   },
   {
    "keyword": "DELICIOUS",
    "all": 16,
    "pos": 13,
    "neg": 3,
    "pctPos": 2.54,
    "pctNeg": 0.6,
    "p90": 0.8125,
    "nb": 1.154,
    "svm": 1.2648
   },
   {
    "keyword": "BRACING",
    "all": 16,
    "pos": 14,
    "neg": 2,
    "pctPos": 2.74,
    "pctNeg": 0.4,
    "p90": 0.875,
    "nb": 1.3617,
    "svm": 0.8719
   },
   {
    "keyword": "DRY",
    "all": 16,
    "pos": 3,
    "neg": 13,
    "pctPos": 0.59,
    "pctNeg": 2.61,
    "p90": 0.1875,
    "nb": -1.1232,
    "svm": 0.0264
   },
   {
    "keyword": "QUINCE",
    "all": 15,
    "pos": 13,
    "neg": 2,
    "pctPos": 2.54,
    "pctNeg": 0.4,
    "p90": 0.8667,
    "nb": 1.7671,
    "svm": 0.7301
   },
   {
    "keyword": "CONSISTENT",
    "all": 15,
    "pos": 7,
    "neg": 8,
    "pctPos": 1.37,
    "pctNeg": 1.6,
    "p90": 0.4667,
    "nb": -0.1582,
    "svm": -0.075
   },
   {
    "keyword": "PLUSH",
    "all": 14,
    "pos": 13,
    "neg": 1,
    "pctPos": 2.54,
    "pctNeg": 0.2,
    "p90": 0.9286,
    "nb": 1.7671,
    "svm": 0.0
   },
   {
    "keyword": "MEDIUM-BODIED",
    "all": 14,
    "pos": 0,
    "neg": 14,
    "pctPos": 0.0,
    "pctNeg": 2.81,
    "p90": 0.0,
    "nb": -2.5896,
    "svm": -0.5566
   },
   {
    "keyword": "FOCUS",
    "all": 14,
    "pos": 13,
    "neg": 1,
    "pctPos": 2.54,
    "pctNeg": 0.2,
    "p90": 0.9286,
    "nb": 1.7671,
    "svm": 0.3345
   },
   {
    "keyword": "AROMATIC",
    "all": 14,
    "pos": 5,
    "neg": 9,
    "pctPos": 0.98,
    "pctNeg": 1.8,
    "p90": 0.3571,
    "nb": -0.4946,
    "svm": -0.16
   },
   {
    "keyword": "APPEALING",
    "all": 14,
    "pos": 10,
    "neg": 4,
    "pctPos": 1.96,
    "pctNeg": 0.8,
    "p90": 0.7143,
    "nb": 0.6685,
    "svm": 1.0091
   },
   {
    "keyword": "PURITY",
    "all": 13,
    "pos": 12,
    "neg": 1,
    "pctPos": 2.35,
    "pctNeg": 0.2,
    "p90": 0.9231,
    "nb": 1.5848,
    "svm": -0.1394
   },
   {
    "keyword": "RIPE APPLE",
    "all": 13,
    "pos": 6,
    "neg": 7,
    "pctPos": 1.17,
    "pctNeg": 1.4,
    "p90": 0.4615,
    "nb": -0.1788,
    "svm": -0.2473
   },
   {
    "keyword": "PEPPER",
    "all": 13,
    "pos": 7,
    "neg": 6,
    "pctPos": 1.37,
    "pctNeg": 1.2,
    "p90": 0.5385,
    "nb": 0.535,
    "svm": 0.461
   },
   {
    "keyword": "TAR",
    "all": 13,
    "pos": 12,
    "neg": 1,
    "pctPos": 2.35,
    "pctNeg": 0.2,
    "p90": 0.9231,
    "nb": 1.5848,
    "svm": 0.2852
   },
   {
    "keyword": "CHARACTER",
    "all": 13,
    "pos": 8,
    "neg": 5,
    "pctPos": 1.57,
    "pctNeg": 1.0,
    "p90": 0.6154,
    "nb": 0.5632,
    "svm": 0.5165
   },
   {
    "keyword": "DARK",
    "all": 13,
    "pos": 13,
    "neg": 0,
    "pctPos": 2.54,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.4603,
    "svm": 1.2242
   },
   {
    "keyword": "DEFT",
    "all": 12,
    "pos": 8,
    "neg": 4,
    "pctPos": 1.57,
    "pctNeg": 0.8,
    "p90": 0.6667,
    "nb": 0.7863,
    "svm": 0.4716
   },
   {
    "keyword": "TOAST",
    "all": 12,
    "pos": 5,
    "neg": 7,
    "pctPos": 0.98,
    "pctNeg": 1.4,
    "p90": 0.4167,
    "nb": -0.5842,
    "svm": -1.0
   },
   {
    "keyword": "GRACE",
    "all": 12,
    "pos": 12,
    "neg": 0,
    "pctPos": 2.35,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.1726,
    "svm": 1.0
   },
   {
    "keyword": "LICORICE",
    "all": 12,
    "pos": 8,
    "neg": 4,
    "pctPos": 1.57,
    "pctNeg": 0.8,
    "p90": 0.6667,
    "nb": 0.6685,
    "svm": 0.526
   },
   {
    "keyword": "STRAWBERRY",
    "all": 12,
    "pos": 1,
    "neg": 11,
    "pctPos": 0.2,
    "pctNeg": 2.2,
    "p90": 0.0833,
    "nb": -1.6341,
    "svm": -0.4592
   },
   {
    "keyword": "BERRY",
    "all": 12,
    "pos": 9,
    "neg": 3,
    "pctPos": 1.76,
    "pctNeg": 0.6,
    "p90": 0.75,
    "nb": 1.074,
    "svm": 0.597
   },
   {
    "keyword": "VIVID",
    "all": 11,
    "pos": 9,
    "neg": 2,
    "pctPos": 1.76,
    "pctNeg": 0.4,
    "p90": 0.8182,
    "nb": 1.4794,
    "svm": 1.0
   },
   {
    "keyword": "TAUT",
    "all": 11,
    "pos": 7,
    "neg": 4,
    "pctPos": 1.37,
    "pctNeg": 0.8,
    "p90": 0.6364,
    "nb": 0.3808,
    "svm": 0.5058
   },
   {
    "keyword": "FINESSE",
    "all": 11,
    "pos": 11,
    "neg": 0,
    "pctPos": 2.15,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.3733,
    "svm": 1.0325
   },
   {
    "keyword": "WARM",
    "all": 10,
    "pos": 6,
    "neg": 4,
    "pctPos": 1.17,
    "pctNeg": 0.8,
    "p90": 0.6,
    "nb": -0.2478,
    "svm": -0.7237
   },
   {
    "keyword": "ECHO",
    "all": 10,
    "pos": 7,
    "neg": 3,
    "pctPos": 1.37,
    "pctNeg": 0.6,
    "p90": 0.7,
    "nb": 0.8227,
    "svm": -0.0523
   },
   {
    "keyword": "LUSCIOUS",
    "all": 10,
    "pos": 9,
    "neg": 1,
    "pctPos": 1.76,
    "pctNeg": 0.2,
    "p90": 0.9,
    "nb": 1.2281,
    "svm": -0.1965
   },
   {
    "keyword": "GREEN FIG",
    "all": 10,
    "pos": 6,
    "neg": 4,
    "pctPos": 1.17,
    "pctNeg": 0.8,
    "p90": 0.6,
    "nb": 0.6685,
    "svm": 0.8527
   },
   {
    "keyword": "SEA SALT",
    "all": 10,
    "pos": 8,
    "neg": 2,
    "pctPos": 1.57,
    "pctNeg": 0.4,
    "p90": 0.8,
    "nb": 0.9562,
    "svm": 0.5394
   },
   {
    "keyword": "BLACK OLIVE",
    "all": 10,
    "pos": 10,
    "neg": 0,
    "pctPos": 1.96,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.0548,
    "svm": 0.2852
   },
   {
    "keyword": "FLEUR DE SEL",
    "all": 10,
    "pos": 6,
    "neg": 4,
    "pctPos": 1.17,
    "pctNeg": 0.8,
    "p90": 0.6,
    "nb": 0.8227,
    "svm": 0.3249
   },
   {
    "keyword": "HAZELNUT",
    "all": 10,
    "pos": 10,
    "neg": 0,
    "pctPos": 1.96,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.9213,
    "svm": 0.8529
   },
   {
    "keyword": "PASSION FRUIT",
    "all": 10,
    "pos": 6,
    "neg": 4,
    "pctPos": 1.17,
    "pctNeg": 0.8,
    "p90": 0.6,
    "nb": 0.1577,
    "svm": -0.3116
   },
   {
    "keyword": "DANCE",
    "all": 9,
    "pos": 1,
    "neg": 8,
    "pctPos": 0.2,
    "pctNeg": 1.6,
    "p90": 0.1111,
    "nb": -1.4109,
    "svm": -0.7471
   },
   {
    "keyword": "BLACK CURRANT",
    "all": 9,
    "pos": 8,
    "neg": 1,
    "pctPos": 1.57,
    "pctNeg": 0.2,
    "p90": 0.8889,
    "nb": 1.2281,
    "svm": 0.4272
   },
   {
    "keyword": "IMPRESSIVE",
    "all": 9,
    "pos": 9,
    "neg": 0,
    "pctPos": 1.76,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.0548,
    "svm": 0.0873
   },
   {
    "keyword": "CEDAR",
    "all": 9,
    "pos": 6,
    "neg": 3,
    "pctPos": 1.17,
    "pctNeg": 0.6,
    "p90": 0.6667,
    "nb": 0.3808,
    "svm": 0.2701
   },
   {
    "keyword": "ORANGE BLOSSOM",
    "all": 9,
    "pos": 6,
    "neg": 3,
    "pctPos": 1.17,
    "pctNeg": 0.6,
    "p90": 0.6667,
    "nb": 0.535,
    "svm": 0.0
   },
   {
    "keyword": "VIOLET",
    "all": 9,
    "pos": 6,
    "neg": 3,
    "pctPos": 1.17,
    "pctNeg": 0.6,
    "p90": 0.6667,
    "nb": 0.535,
    "svm": 0.4272
   },
   {
    "keyword": "BEAM",
    "all": 9,
    "pos": 4,
    "neg": 5,
    "pctPos": 0.78,
    "pctNeg": 1.0,
    "p90": 0.4444,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "GINGER",
    "all": 9,
    "pos": 5,
    "neg": 4,
    "pctPos": 0.98,
    "pctNeg": 0.8,
    "p90": 0.5556,
    "nb": 0.4862,
    "svm": 0.0
   },
   {
    "keyword": "ANISE",
    "all": 9,
    "pos": 9,
    "neg": 0,
    "pctPos": 1.76,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.9213,
    "svm": 0.0
   },
   {
    "keyword": "WEIGHT",
    "all": 8,
    "pos": 8,
    "neg": 0,
    "pctPos": 1.57,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 2.0548,
    "svm": 0.2242
   },
   {
    "keyword": "WILD BERRY",
    "all": 8,
    "pos": 7,
    "neg": 1,
    "pctPos": 1.37,
    "pctNeg": 0.2,
    "p90": 0.875,
    "nb": 1.3617,
    "svm": 0.3528
   },
   {
    "keyword": "SAGE",
    "all": 8,
    "pos": 6,
    "neg": 2,
    "pctPos": 1.17,
    "pctNeg": 0.4,
    "p90": 0.75,
    "nb": 0.4862,
    "svm": 0.8797
   },
   {
    "keyword": "POMEGRANATE",
    "all": 7,
    "pos": 1,
    "neg": 6,
    "pctPos": 0.2,
    "pctNeg": 1.2,
    "p90": 0.1429,
    "nb": -0.9409,
    "svm": 0.4593
   },
   {
    "keyword": "WELL-INTEGRATED",
    "all": 7,
    "pos": 7,
    "neg": 0,
    "pctPos": 1.37,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.7671,
    "svm": 0.0752
   },
   {
    "keyword": "LEMON-LIME",
    "all": 7,
    "pos": 2,
    "neg": 5,
    "pctPos": 0.39,
    "pctNeg": 1.0,
    "p90": 0.2857,
    "nb": -0.3123,
    "svm": -0.5027
   },
   {
    "keyword": "MINT",
    "all": 7,
    "pos": 3,
    "neg": 4,
    "pctPos": 0.59,
    "pctNeg": 0.8,
    "p90": 0.4286,
    "nb": -0.0246,
    "svm": 0.3402
   },
   {
    "keyword": "BLUEBERRY",
    "all": 7,
    "pos": 5,
    "neg": 2,
    "pctPos": 0.98,
    "pctNeg": 0.4,
    "p90": 0.7143,
    "nb": 0.2631,
    "svm": 0.1692
   },
   {
    "keyword": "COFFEE",
    "all": 7,
    "pos": 7,
    "neg": 0,
    "pctPos": 1.37,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.9213,
    "svm": 0.0
   },
   {
    "keyword": "OAK",
    "all": 7,
    "pos": 5,
    "neg": 2,
    "pctPos": 0.98,
    "pctNeg": 0.4,
    "p90": 0.7143,
    "nb": 0.4862,
    "svm": 0.0
   },
   {
    "keyword": "CINNAMON",
    "all": 7,
    "pos": 5,
    "neg": 2,
    "pctPos": 0.98,
    "pctNeg": 0.4,
    "p90": 0.7143,
    "nb": 1.074,
    "svm": 0.0114
   },
   {
    "keyword": "PERSISTENT",
    "all": 6,
    "pos": 3,
    "neg": 3,
    "pctPos": 0.59,
    "pctNeg": 0.6,
    "p90": 0.5,
    "nb": -0.3123,
    "svm": -0.3383
   },
   {
    "keyword": "CHALKY",
    "all": 6,
    "pos": 1,
    "neg": 5,
    "pctPos": 0.2,
    "pctNeg": 1.0,
    "p90": 0.1667,
    "nb": -1.8164,
    "svm": -0.2577
   },
   {
    "keyword": "WHITE FRUIT",
    "all": 6,
    "pos": 4,
    "neg": 2,
    "pctPos": 0.78,
    "pctNeg": 0.4,
    "p90": 0.6667,
    "nb": 0.2631,
    "svm": 0.0
   },
   {
    "keyword": "FLESHY",
    "all": 6,
    "pos": 4,
    "neg": 2,
    "pctPos": 0.78,
    "pctNeg": 0.4,
    "p90": 0.6667,
    "nb": 0.4862,
    "svm": 0.1604
   },
   {
    "keyword": "ALLURING",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.7671,
    "svm": 0.5021
   },
   {
    "keyword": "LYCHEE",
    "all": 6,
    "pos": 2,
    "neg": 4,
    "pctPos": 0.39,
    "pctNeg": 0.8,
    "p90": 0.3333,
    "nb": -0.3123,
    "svm": 0.2868
   },
   {
    "keyword": "CHERRY PIE",
    "all": 6,
    "pos": 1,
    "neg": 5,
    "pctPos": 0.2,
    "pctNeg": 1.0,
    "p90": 0.1667,
    "nb": -1.1232,
    "svm": -0.0284
   },
   {
    "keyword": "PRESENCE",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.7671,
    "svm": 0.4419
   },
   {
    "keyword": "DAMSON PLUM",
    "all": 6,
    "pos": 1,
    "neg": 5,
    "pctPos": 0.2,
    "pctNeg": 1.0,
    "p90": 0.1667,
    "nb": -1.6341,
    "svm": 0.0
   },
   {
    "keyword": "STRONG FINISH",
    "all": 6,
    "pos": 5,
    "neg": 1,
    "pctPos": 0.98,
    "pctNeg": 0.2,
    "p90": 0.8333,
    "nb": 0.8917,
    "svm": -0.2693
   },
   {
    "keyword": "ROSE",
    "all": 6,
    "pos": 2,
    "neg": 4,
    "pctPos": 0.39,
    "pctNeg": 0.8,
    "p90": 0.3333,
    "nb": -0.3123,
    "svm": -0.2361
   },
   {
    "keyword": "DASH",
    "all": 6,
    "pos": 2,
    "neg": 4,
    "pctPos": 0.39,
    "pctNeg": 0.8,
    "p90": 0.3333,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "DETAILED",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 1.0
   },
   {
    "keyword": "HANG",
    "all": 6,
    "pos": 1,
    "neg": 5,
    "pctPos": 0.2,
    "pctNeg": 1.0,
    "p90": 0.1667,
    "nb": -0.9409,
    "svm": -0.3305
   },
   {
    "keyword": "DEEP",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.0
   },
   {
    "keyword": "GREEN TEA",
    "all": 6,
    "pos": 4,
    "neg": 2,
    "pctPos": 0.78,
    "pctNeg": 0.4,
    "p90": 0.6667,
    "nb": 0.2631,
    "svm": -0.1878
   },
   {
    "keyword": "GREEN OLIVE",
    "all": 6,
    "pos": 5,
    "neg": 1,
    "pctPos": 0.98,
    "pctNeg": 0.2,
    "p90": 0.8333,
    "nb": 0.8917,
    "svm": 0.0795
   },
   {
    "keyword": "BOLD",
    "all": 6,
    "pos": 3,
    "neg": 3,
    "pctPos": 0.59,
    "pctNeg": 0.6,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": -0.2267
   },
   {
    "keyword": "TREMENDOUS",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.9213,
    "svm": 0.0
   },
   {
    "keyword": "TEA",
    "all": 6,
    "pos": 5,
    "neg": 1,
    "pctPos": 0.98,
    "pctNeg": 0.2,
    "p90": 0.8333,
    "nb": 0.6685,
    "svm": 0.7757
   },
   {
    "keyword": "DARK PLUM",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.7671,
    "svm": 0.9326
   },
   {
    "keyword": "TOASTY OAK",
    "all": 6,
    "pos": 6,
    "neg": 0,
    "pctPos": 1.17,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.7738
   },
   {
    "keyword": "LIFT",
    "all": 6,
    "pos": 5,
    "neg": 1,
    "pctPos": 0.98,
    "pctNeg": 0.2,
    "p90": 0.8333,
    "nb": 1.074,
    "svm": 0.3275
   },
   {
    "keyword": "BUTTERSCOTCH",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.0
   },
   {
    "keyword": "SANDALWOOD",
    "all": 5,
    "pos": 4,
    "neg": 1,
    "pctPos": 0.78,
    "pctNeg": 0.2,
    "p90": 0.8,
    "nb": 0.3808,
    "svm": 0.0244
   },
   {
    "keyword": "BOYSENBERRY",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.6385
   },
   {
    "keyword": "CARDAMOM",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.0
   },
   {
    "keyword": "TOFFEE",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.1331
   },
   {
    "keyword": "VELVETY",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "EXPANSIVE",
    "all": 5,
    "pos": 4,
    "neg": 1,
    "pctPos": 0.78,
    "pctNeg": 0.2,
    "p90": 0.8,
    "nb": 0.6685,
    "svm": 0.406
   },
   {
    "keyword": "DARK BERRY",
    "all": 5,
    "pos": 5,
    "neg": 0,
    "pctPos": 0.98,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 1.213
   },
   {
    "keyword": "LEMON PEEL",
    "all": 5,
    "pos": 2,
    "neg": 3,
    "pctPos": 0.39,
    "pctNeg": 0.6,
    "p90": 0.4,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "MOCHA",
    "all": 4,
    "pos": 3,
    "neg": 1,
    "pctPos": 0.59,
    "pctNeg": 0.2,
    "p90": 0.75,
    "nb": 0.6685,
    "svm": 0.2457
   },
   {
    "keyword": "SASSAFRAS",
    "all": 4,
    "pos": 3,
    "neg": 1,
    "pctPos": 0.59,
    "pctNeg": 0.2,
    "p90": 0.75,
    "nb": 1.3617,
    "svm": 0.0752
   },
   {
    "keyword": "TIGHTLY WOUND",
    "all": 4,
    "pos": 3,
    "neg": 1,
    "pctPos": 0.59,
    "pctNeg": 0.2,
    "p90": 0.75,
    "nb": 0.6685,
    "svm": 0.1847
   },
   {
    "keyword": "RAISIN",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.2173
   },
   {
    "keyword": "BAY LEAF",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "RED BERRY",
    "all": 4,
    "pos": 3,
    "neg": 1,
    "pctPos": 0.59,
    "pctNeg": 0.2,
    "p90": 0.75,
    "nb": 0.3808,
    "svm": 0.0873
   },
   {
    "keyword": "SUAVE",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.1527
   },
   {
    "keyword": "DEVELOP",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0631
   },
   {
    "keyword": "STUNNING",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "FLAVORFUL",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.5641
   },
   {
    "keyword": "COCOA",
    "all": 4,
    "pos": 1,
    "neg": 3,
    "pctPos": 0.2,
    "pctNeg": 0.6,
    "p90": 0.25,
    "nb": -1.1232,
    "svm": 0.0
   },
   {
    "keyword": "BLACK PEPPER",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.5848,
    "svm": 0.0
   },
   {
    "keyword": "BLACK TEA",
    "all": 4,
    "pos": 4,
    "neg": 0,
    "pctPos": 0.78,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "STEELY",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.878
   },
   {
    "keyword": "SOLID",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": 0.3808,
    "svm": 0.914
   },
   {
    "keyword": "SNAPPY",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.656
   },
   {
    "keyword": "SWEET SPICE",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.0
   },
   {
    "keyword": "TALCUM",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.4301,
    "svm": 0.472
   },
   {
    "keyword": "BANANA",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.4301,
    "svm": 0.6201
   },
   {
    "keyword": "BAKED PEAR",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "LEMON CUSTARD",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.4301,
    "svm": 0.2491
   },
   {
    "keyword": "YOUNG",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.304
   },
   {
    "keyword": "SATINY",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": 0.3808,
    "svm": -0.5014
   },
   {
    "keyword": "CREAMY OAK",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": 0.3808,
    "svm": 0.9544
   },
   {
    "keyword": "DRIPPING",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": -0.0246,
    "svm": -0.1791
   },
   {
    "keyword": "WONDERFUL",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "ESPRESSO",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.8302
   },
   {
    "keyword": "MUSCLE",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "ENGAGING",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0799
   },
   {
    "keyword": "TOASTED HAZELNUT",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": 0.3808,
    "svm": -0.1817
   },
   {
    "keyword": "FRESH-CUT APPLE",
    "all": 3,
    "pos": 0,
    "neg": 3,
    "pctPos": 0.0,
    "pctNeg": 0.6,
    "p90": 0.0,
    "nb": -1.1232,
    "svm": -0.5766
   },
   {
    "keyword": "TOMATO LEAF",
    "all": 3,
    "pos": 2,
    "neg": 1,
    "pctPos": 0.39,
    "pctNeg": 0.2,
    "p90": 0.6667,
    "nb": -0.7178,
    "svm": -0.1336
   },
   {
    "keyword": "DRIED CHERRY",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.0246,
    "svm": -0.4592
   },
   {
    "keyword": "DRIED BERRY",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.4301,
    "svm": 0.8878
   },
   {
    "keyword": "CASSIS",
    "all": 3,
    "pos": 3,
    "neg": 0,
    "pctPos": 0.59,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.3617,
    "svm": 0.0
   },
   {
    "keyword": "ASPARAGUS",
    "all": 3,
    "pos": 1,
    "neg": 2,
    "pctPos": 0.2,
    "pctNeg": 0.4,
    "p90": 0.3333,
    "nb": -0.4301,
    "svm": 0.0
   },
   {
    "keyword": "GANACHE",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.4702
   },
   {
    "keyword": "DELICACY",
    "all": 2,
    "pos": 1,
    "neg": 1,
    "pctPos": 0.2,
    "pctNeg": 0.2,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "JAMMY",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "ENCORE",
    "all": 2,
    "pos": 1,
    "neg": 1,
    "pctPos": 0.2,
    "pctNeg": 0.2,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": 0.1746
   },
   {
    "keyword": "KEY LIME PIE",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.8864
   },
   {
    "keyword": "AGE WELL",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.0
   },
   {
    "keyword": "AUSTERE",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -1.1232,
    "svm": -0.2388
   },
   {
    "keyword": "BLACK LICORICE",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.0
   },
   {
    "keyword": "LEAF",
    "all": 2,
    "pos": 1,
    "neg": 1,
    "pctPos": 0.2,
    "pctNeg": 0.2,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "LILAC",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.0
   },
   {
    "keyword": "PURE-TASTING",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 1.0
   },
   {
    "keyword": "LIME BLOSSOM",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "DARK CHERRY",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "BUBBLE GUM",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -1.1232,
    "svm": 0.0
   },
   {
    "keyword": "PERSONALITY",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "REMARKABLE",
    "all": 2,
    "pos": 2,
    "neg": 0,
    "pctPos": 0.39,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 1.074,
    "svm": 0.1266
   },
   {
    "keyword": "PRUNE",
    "all": 2,
    "pos": 1,
    "neg": 1,
    "pctPos": 0.2,
    "pctNeg": 0.2,
    "p90": 0.5,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "CITRUS BLOSSOM",
    "all": 2,
    "pos": 0,
    "neg": 2,
    "pctPos": 0.0,
    "pctNeg": 0.4,
    "p90": 0.0,
    "nb": -1.1232,
    "svm": -0.1864
   },
   {
    "keyword": "MOLASSES",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "CURRANT CONFITURE",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": -0.87
   },
   {
    "keyword": "NOT HEAVY",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "CLEMENTINE",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "ENORMOUS RANGE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "DIMENSION",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "POTENTIAL",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "CORE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.047
   },
   {
    "keyword": "POISED",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "ARRAY OF FLAVORS",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "MEDICINAL",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "EUCALYPTUS",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "FLESH",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "FUN",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "MOMENTUM",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "APPROACHABLE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "BACON",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "FULL-BLOWN",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "PEONY",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": -0.163
   },
   {
    "keyword": "FRUITCAKE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "WALNUT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "PERFUMED",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "ELECTRIC",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "WEIGHTLESS",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "WELL-CRAFTED",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0291
   },
   {
    "keyword": "COMPLEMENT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.5525
   },
   {
    "keyword": "DENSE CLOUD",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "GRAPEY",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": -0.2832
   },
   {
    "keyword": "SOY SAUCE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "DECEPTIVELY",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0752
   },
   {
    "keyword": "LATENT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "BLACKBERRY JAM",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "SERIOUS",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "SHARPLY DEFINED",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "LEMON BLOSSOM",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 1.0
   },
   {
    "keyword": "ROASTED RED PEPPER",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "ROASTED BEET",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "OLIVE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "RIVETING",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "DARK CHOCOLATE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "SOUR",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.7178,
    "svm": 0.0
   },
   {
    "keyword": "BLACK FRUIT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "DAZZLING",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "SPICY OAK",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "STEEPED BLACK CURRANT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "DEEP WELL",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.2173
   },
   {
    "keyword": "HOVER",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "BRAMBLE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "BITTERSWEET",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "RED FRUIT",
    "all": 1,
    "pos": 0,
    "neg": 1,
    "pctPos": 0.0,
    "pctNeg": 0.2,
    "p90": 0.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "HOT EARTH",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "BRILLIANT",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "SWEATY",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   },
   {
    "keyword": "RAUCOUS",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": -0.0246,
    "svm": 0.0
   },
   {
    "keyword": "BROWN SPICE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.5233
   },
   {
    "keyword": "NUANCE",
    "all": 1,
    "pos": 1,
    "neg": 0,
    "pctPos": 0.2,
    "pctNeg": 0.0,
    "p90": 1.0,
    "nb": 0.6685,
    "svm": 0.0
   }
  ],
  "agreed": [
   "APRICOT",
   "BEAUTY",
   "CONCENTRATED",
   "DARK",
   "ELEGANT",
   "EXPRESSIVE",
   "FINESSE",
   "FULL-BODIED",
   "HONEY",
   "LONG",
   "LONG FINISH",
   "POWER"
  ],
  "agreedAll": [
   "APRICOT",
   "BEAUTY",
   "EXPRESSIVE",
   "LONG",
   "LONG FINISH"
  ]
 }
};
